/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package orchard;

import au.com.bytecode.opencsv.CSVReader;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.ListModel;

/**
 *
 * @author Chris
 */
public class OrchardNewTransformation extends javax.swing.JFrame {

    /**
     * Creates new form CilantroTransformation
     */
    public OrchardNewTransformation() {
        initComponents();
        addActionListeners();
        createCellTypeButtonGroup();
        createTfnMethodButtonGroup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfnMethodButtonGroup = new javax.swing.ButtonGroup();
        cellTypeButtonGroup = new javax.swing.ButtonGroup();
        cellTypeLabel = new javax.swing.JLabel();
        pJV53Button = new javax.swing.JRadioButton();
        wtButton = new javax.swing.JRadioButton();
        batchNameLabel = new javax.swing.JLabel();
        batchInputField = new javax.swing.JTextField();
        tfnEffLabel = new javax.swing.JLabel();
        tfnField = new javax.swing.JTextField();
        notebookLocationLabel = new javax.swing.JLabel();
        notebookNumLabel = new javax.swing.JLabel();
        startPageLabel = new javax.swing.JLabel();
        endPageLabel = new javax.swing.JLabel();
        notebookInputField = new javax.swing.JTextField();
        startPageInputField = new javax.swing.JTextField();
        endPageInputField = new javax.swing.JTextField();
        importTfnButton = new javax.swing.JButton();
        controlPlasmidLabel = new javax.swing.JLabel();
        controlPlasmidField = new javax.swing.JTextField();
        tfnMethodLabel = new javax.swing.JLabel();
        cuvetteButton = new javax.swing.JRadioButton();
        nineSixPlateButton = new javax.swing.JRadioButton();
        twoFiveWellPlateButton = new javax.swing.JRadioButton();
        newTfnBanner = new javax.swing.JLabel();
        createNewTfnButton = new javax.swing.JButton();
        timeConstantField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        dateFieldLabel = new javax.swing.JLabel();
        timeConstantFieldLabel = new javax.swing.JLabel();
        selectedFileLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cellTypeLabel.setText("Electrocomptent Cell Type");

        pJV53Button.setText("M. smegmatis mc2155:pJV53");

        wtButton.setText("M. smegmatis mc2155 WT");

        batchNameLabel.setText("Batch Name:");

        batchInputField.setText("Batch");

        tfnEffLabel.setText("Tfn Efficiency:");

        tfnField.setText("Efficiency");

        notebookLocationLabel.setText("Notebook Location");

        notebookNumLabel.setText("Notebook #:");

        startPageLabel.setText("Start Page:");

        endPageLabel.setText("End Page:");

        notebookInputField.setText("Notebook #");

        startPageInputField.setText("Start Page");

        endPageInputField.setText("End Page");

        importTfnButton.setLabel("Import  CSV");

        controlPlasmidLabel.setText("Control Plasmid:");

        controlPlasmidField.setText("Plasmid");

        tfnMethodLabel.setText("Transformation Method");

        cuvetteButton.setText("Single Cuvette");

        nineSixPlateButton.setSelected(true);
        nineSixPlateButton.setText("96 Well Plate");

        twoFiveWellPlateButton.setText("25 Well Plate");

        newTfnBanner.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newTfnBanner.setText("New Transformation");

        createNewTfnButton.setText("Create New Transformation");

        timeConstantField.setText("00.0");

        dateField.setText("YYYY-MM-DD");

        dateFieldLabel.setText("Tfn Date:");

        timeConstantFieldLabel.setText("Time Constant (ms):");
        timeConstantFieldLabel.setToolTipText("");

        selectedFileLabel.setText("Select File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(batchNameLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(141, 141, 141)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(endPageLabel)
                                        .addComponent(startPageLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(startPageInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(endPageInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(batchInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addComponent(wtButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(155, 155, 155)
                                    .addComponent(pJV53Button)))
                            .addGap(39, 39, 39))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(notebookNumLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(notebookInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(95, 95, 95)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(tfnMethodLabel)
                        .addGap(67, 67, 67)
                        .addComponent(notebookLocationLabel)
                        .addGap(129, 129, 129))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeConstantFieldLabel)
                            .addComponent(tfnEffLabel)
                            .addComponent(controlPlasmidLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(controlPlasmidField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeConstantField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(twoFiveWellPlateButton)
                                    .addComponent(cuvetteButton)
                                    .addComponent(nineSixPlateButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(importTfnButton)
                                .addGap(18, 18, 18)
                                .addComponent(selectedFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateFieldLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cellTypeLabel))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createNewTfnButton)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(newTfnBanner)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(newTfnBanner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewTfnButton)
                    .addComponent(importTfnButton)
                    .addComponent(selectedFileLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controlPlasmidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(controlPlasmidLabel)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFieldLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnEffLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeConstantFieldLabel)
                            .addComponent(timeConstantField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batchNameLabel)
                            .addComponent(batchInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(tfnMethodLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuvetteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(twoFiveWellPlateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nineSixPlateButton)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(cellTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pJV53Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wtButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notebookLocationLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notebookNumLabel)
                            .addComponent(notebookInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startPageInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startPageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endPageLabel)
                            .addComponent(endPageInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );

        dateFieldLabel.getAccessibleContext().setAccessibleName("jLable1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrchardNewTransformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrchardNewTransformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrchardNewTransformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrchardNewTransformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrchardNewTransformation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batchInputField;
    private javax.swing.JLabel batchNameLabel;
    private javax.swing.ButtonGroup cellTypeButtonGroup;
    private javax.swing.JLabel cellTypeLabel;
    private javax.swing.JTextField controlPlasmidField;
    private javax.swing.JLabel controlPlasmidLabel;
    private javax.swing.JButton createNewTfnButton;
    private javax.swing.JRadioButton cuvetteButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateFieldLabel;
    private javax.swing.JTextField endPageInputField;
    private javax.swing.JLabel endPageLabel;
    private javax.swing.JButton importTfnButton;
    private javax.swing.JLabel newTfnBanner;
    private javax.swing.JRadioButton nineSixPlateButton;
    private javax.swing.JTextField notebookInputField;
    private javax.swing.JLabel notebookLocationLabel;
    private javax.swing.JLabel notebookNumLabel;
    private javax.swing.JRadioButton pJV53Button;
    private javax.swing.JLabel selectedFileLabel;
    private javax.swing.JTextField startPageInputField;
    private javax.swing.JLabel startPageLabel;
    private javax.swing.JLabel tfnEffLabel;
    private javax.swing.JTextField tfnField;
    private javax.swing.ButtonGroup tfnMethodButtonGroup;
    private javax.swing.JLabel tfnMethodLabel;
    private javax.swing.JTextField timeConstantField;
    private javax.swing.JLabel timeConstantFieldLabel;
    private javax.swing.JRadioButton twoFiveWellPlateButton;
    private javax.swing.JRadioButton wtButton;
    // End of variables declaration//GEN-END:variables
    private File csvFile = null;
    /*batchInputField
     cellTypeButtonGroup
     controlPlasmidField
     endPageInputField
     startPageInputField
     tfnField
     tfnGeneList
     tfnMethodButtonGroup
     */
    public String getTimeConstant(){
        return timeConstantField.getText();
    }
    public String getTfnDate(){
        return dateField.getText();
    }
    public String getNotebook(){
        return notebookInputField.getText();
    }
    public String getBatchInputField() {
        return batchInputField.getText();
    }

    public String getCellType() {
        return cellTypeButtonGroup.getSelection().getActionCommand();
    }

    public String getControlPlasmid() {
        return controlPlasmidField.getText();
    }

    public String getEndPage() {
        return endPageInputField.getText();
    }

    public String getStartPage() {
        return startPageInputField.getText();
    }

    public String getTfnField() {
        return tfnField.getText();
    }

    public String getTfnMethod() {
        return tfnMethodButtonGroup.getSelection().getActionCommand();
    }

    

    /*public String[] getGeneListGenes() {
        ListModel model = tfnGeneList.getModel();
        int modelSize = model.getSize();
        String[] genes = new String[modelSize];
        for (int i = 0; i < modelSize; i++) {
            genes[i] = model.getElementAt(i).toString();
        }
        return genes;
    }*/
    
    private void setFile(File file){
        csvFile = file;
    }
    
    private File getFile(){
        return csvFile;
    }

    private void addActionListeners() {
        NewTransformationActionListener listener = new NewTransformationActionListener();

        createNewTfnButton.addActionListener(listener);
        //showGeneStatsButton.addActionListener(listener);
        importTfnButton.addActionListener(listener);
    }

    private void createCellTypeButtonGroup() {
        cellTypeButtonGroup.add(pJV53Button);
        cellTypeButtonGroup.add(wtButton);
    }

    private void createTfnMethodButtonGroup() {

        tfnMethodButtonGroup.add(cuvetteButton);
        tfnMethodButtonGroup.add(twoFiveWellPlateButton);
        tfnMethodButtonGroup.add(nineSixPlateButton);
    }

    class NewTransformationActionListener implements ActionListener {

        /*private DatabaseConnector connection = null;
         private Connection dbConnection = null;

         private void connectToDatabase() {

         try {
         connection = new DatabaseConnector();
         dbConnection = connection.connectDB();
         } catch (Exception e) {
         System.out.println("Unable to connect to database");
         }
         }

         private void disconnectFromDatabase() {
         connection.closeDBConnection(dbConnection);
         }*/
        @Override
        public void actionPerformed(ActionEvent e) {
            Object source = e.getSource();
            /*if (source == showGeneStatsButton) {
                OrchardGeneStats geneStats = new OrchardGeneStats();
                DatabaseConnector dbConnector = new DatabaseConnector();
                Connection dbConnection = null;
                try {
                    dbConnection = dbConnector.connectDB();
                } catch (SQLException ex) {
                    Logger.getLogger(OrchardGeneInfo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(OrchardGeneInfo.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    //query
                    dbConnector.closeDBConnection(dbConnection);
                } catch (SQLException ex) {
                    Logger.getLogger(OrchardGeneInfo.class.getName()).log(Level.SEVERE, null, ex);
                }

                geneStats.setColonyCount(null);
                geneStats.setKOProduced(null);
                geneStats.setShared(null);
                geneStats.setSharedWith(null);
                geneStats.setTfnNum(null);

                geneStats.setVisible(true);

            }*/

            if (source == importTfnButton) {
                JFileChooser importCSVBox = new JFileChooser();
                int result = importCSVBox.showOpenDialog(OrchardNewTransformation.this);
                if (result == JFileChooser.APPROVE_OPTION) {
                    //new OrchardImportCSV(importCSVBox.getSelectedFile());
                    System.out.println(importCSVBox.getSelectedFile());
                    selectedFileLabel.setText(importCSVBox.getSelectedFile().getName());
                    setFile(importCSVBox.getSelectedFile());
                    //importCSVBox.
                    //log.append("Opening");
                } else if (result == JFileChooser.CANCEL_OPTION) {
                    System.out.println("Cancel");
                }
                //System.out.println("1");
                /*DefaultListModel geneListModel = new DefaultListModel();

                //get info from csv
                //for each gene name
                geneListModel.addElement("");

                setGeneList(new JList(geneListModel));*/
                //System.out.println("2");
            }

            if (source == createNewTfnButton) {
                //String gene = selectedGeneList.getSelectedValue().toString();
                System.out.println(csvFile);
                DatabaseConnector dbConnector = new DatabaseConnector();
                ResultSet rs = null;
                Connection dbConnection = null;
                PreparedStatement stmt = null;
                PreparedStatement tfnStmt = null;
                CSVReader reader = null;
                try {
                    reader = new CSVReader(new FileReader(getFile()));
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(OrchardNewTransformation.class.getName()).log(Level.SEVERE, null, ex);
                }

                try {

                    dbConnection = dbConnector.connectDB();

                    //stmt = dbConnection.prepareStatement("Select * from Gene Where Locus = '" + gene + "'");
                    String sql = null;

                    //Need to insert into parent tables first
                    String sqlTransformation = "Insert into Transformation(Date, Efficiency, Plasmid, TimeConstant,"
                            + "Notebook, Start_Page, Stop_Page, Method, Comp_Cells_Batch) "
                            + "values (?,?,?,?,?,?,?,?,?)";

                    tfnStmt = dbConnection.prepareStatement(sqlTransformation);
                     tfnStmt.setString(1,getTfnDate());
                     tfnStmt.setString(2, getTfnField());
                     tfnStmt.setString(3, getControlPlasmid());
                     tfnStmt.setString(4, getTimeConstant()); //time constant
                     tfnStmt.setString(5, getNotebook());
                     tfnStmt.setString(6, getStartPage());
                     tfnStmt.setString(7, getEndPage());
                     tfnStmt.setString(8, getTfnMethod());
                     tfnStmt.setString(9, getBatchInputField());
                     System.out.println(tfnStmt.toString());
                     System.out.println("About to execute tfn stmt");
                     tfnStmt.execute();
                     System.out.println("Finished execute tfn stmt");
                    //Insert info into Transformation_has_Gene Table
                    String sqlTransformationHasGene = "Insert into Transformation_has_Gene (Transformation_Date, Gene_Locus, Gene_Plate_idPlate,"
                            + "TimeConstant, Colonies, Shared, SharedWith, TfnNumber, KOProduced, Notes, DNA_Amt) "
                            + "values (?,?,?,?,?,?,?,?,?,?,?)";

                    stmt = dbConnection.prepareStatement(sqlTransformationHasGene);
                    int stmtCount = 0;

                    String[] nextLine;
                    int next = 0;
                    while ((nextLine = reader.readNext()) != null) {

                        stmt.setString(1, getTfnDate()); //Tfn Date
                        stmt.setString(2, nextLine[0]); //Gene Locus
                        stmt.setString(3, nextLine[1]); //Gene_Plate_idPlate
                        stmt.setString(4, nextLine[2]); //DNA Amount
                        stmt.setString(5, nextLine[3]); //Time Constant
                        stmt.setString(6, nextLine[4]); //Shared
                        stmt.setString(7, nextLine[5]); //SharedWith
                        stmt.setString(8, nextLine[6]); //TfnNumber
                        stmt.setString(9, nextLine[7]); //KOProduced
                        stmt.setString(10, nextLine[8]); //Notes
                        stmt.setString(11, nextLine[9]); //colonies
                        stmt.addBatch();
                        System.out.println(stmt);
                        System.out.println("Next: "+next);
                                

                        if (++stmtCount % 1000 == 0) {
                            System.out.println("About to execute in 1000 batch");
                            stmt.executeBatch();
                            System.out.println("About to execute in 1000 batch");
                        }
                        next++;
                    }
                    System.out.println("About to execute final batch");
                    stmt.executeBatch();
                    System.out.println("About to execute final batch");
                } catch (SQLException | ClassNotFoundException f) {
                    System.out.println("Unable to connect 3");
                    System.out.println(f);
                } catch (IOException ex) {
                    Logger.getLogger(OrchardNewTransformation.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        dbConnector.closeDBConnection(dbConnection);
                    } catch (SQLException ex) {
                        Logger.getLogger(OrchardMainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } else {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                //System.out.println("Source: " + source);
            }

        }

    }

}
